export const Colors = {
  primary: "#2563EB",
  primaryLight: "#3B82F6",
  primaryDark: "#1D4ED8",
  secondary: "#F97316",
  secondaryLight: "#FB923C",
  secondaryDark: "#EA580C",
  navy: "#1E293B",
  background: "#F8FAFC",
  surface: "#FFFFFF",
  text: "#1E293B",
  textSecondary: "#64748B",
  textMuted: "#94A3B8",
  textPrimary: "#1E293B",
  border: "#E2E8F0",
  error: "#EF4444",
  danger: "#EF4444",
  warning: "#F59E0B",
  success: "#10B981",
  info: "#3B82F6",
  white: "#FFFFFF",
  gray: "#6B7280",
  lightGray: "#F3F4F6",
  successLight: "#D1FAE5",
  warningLight: "#FEF3C7",
  errorLight: "#FEE2E2",
  card: "#FFFFFF",
  primaryLight2: "#DBEAFE",
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const FontSize = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 18,
  xl: 20,
  xxl: 24,
  title: 28,
  header: 32,
};

export const JobStatus: Record<string, { label: string; color: string }> = {
  draft: { label: "Draft", color: Colors.textMuted },
  searching: { label: "Searching", color: Colors.warning },
  worker_assigned: { label: "Assigned", color: Colors.info },
  worker_accepted: { label: "Accepted", color: Colors.info },
  on_the_way: { label: "On The Way", color: Colors.primaryLight },
  arrived: { label: "Arrived", color: Colors.primary },
  work_started: { label: "Work Started", color: Colors.primaryDark },
  in_progress: { label: "In Progress", color: Colors.primary },
  waiting_approval: { label: "Waiting Approval", color: Colors.warning },
  completion_requested: { label: "Completion Requested", color: Colors.warning },
  completed: { label: "Completed", color: Colors.success },
  paid: { label: "Paid", color: Colors.success },
  closed: { label: "Closed", color: Colors.textMuted },
  cancelled: { label: "Cancelled", color: Colors.error },
  disputed: { label: "Disputed", color: Colors.error },
};
